{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unifi-nvr.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-nvr.labels" . | nindent 4 }}
    component: config
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.videos.enabled (not .Values.persistence.videos.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unifi-nvr.fullname" . }}-videos
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi-nvr.labels" . | nindent 4 }}
    component: videos
spec:
  accessModes:
  - {{ .Values.persistence.videos.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.videos.size | quote }}
{{- if .Values.persistence.videos.storageClass }}
  storageClassName: {{ .Values.persistence.videos.storageClass | quote }}
{{- end }}
{{- end }}