apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contao-cms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contao-cms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "contao-cms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "contao-cms.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.secretName" . }}
                  key: DATABASE_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.database.name }}
            - name: MYSQL_USER
              value: {{ .Values.database.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.secretName" . }}
                  key: DATABASE_PASSWORD
          ports:
            - name: tcp
              containerPort: 3306
              protocol: TCP
          volumeMounts:
{{- if .Values.persistence.database.enabled }}
            - name: database
              mountPath: /var/lib/mysql
{{- if .Values.persistence.database.subPath }}
              subPath: {{ .Values.persistence.database.subPath }}
{{- end }}
{{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: PUID
              value: {{ .Values.puid | quote }}
            - name: PGID
              value: {{ .Values.pgid | quote }}
            - name: DOCUMENTROOT
              value: {{ .Values.documentroot | quote }}
            - name: APP_ENV
              value: {{ .Values.appenv | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          volumeMounts:
{{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: /opt/app-root/src/app/config
{{- if .Values.persistence.config.subPath }}
              subPath: {{ .Values.persistence.config.subPath }}
{{- end }}
{{- end }}
{{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: /opt/app-root/src/files
{{- if .Values.persistence.data.subPath }}
              subPath: {{ .Values.persistence.data.subPath }}
{{- end }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
{{- if .Values.persistence.config.existingClaim }}
            claimName: {{ .Values.persistence.config.existingClaim }}
{{- else }}
            claimName: {{ include "contao-cms.fullname" . }}-config
{{- end }}
{{- end }}
{{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
{{- if .Values.persistence.data.existingClaim }}
            claimName: {{ .Values.persistence.data.existingClaim }}
{{- else }}
            claimName: {{ include "contao-cms.fullname" . }}-data
{{- end }}
{{- end }}
{{- if .Values.persistence.database.enabled }}
        - name: database
          persistentVolumeClaim:
{{- if .Values.persistence.database.existingClaim }}
            claimName: {{ .Values.persistence.database.existingClaim }}
{{- else }}
            claimName: {{ include "contao-cms.fullname" . }}-database
{{- end }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
