{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "contao-cms.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contao-cms.labels" . | nindent 4 }}
    component: config
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
{{- end }}
{{- end }}
{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "contao-cms.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contao-cms.labels" . | nindent 4 }}
    component: data
spec:
  accessModes:
  - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
{{- end }}
{{- end }}
{{- if and .Values.persistence.database.enabled (not .Values.persistence.database.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "contao-cms.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contao-cms.labels" . | nindent 4 }}
    component: database
spec:
  accessModes:
  - {{ .Values.persistence.database.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.database.size | quote }}
{{- if .Values.persistence.database.storageClass }}
  storageClassName: {{ .Values.persistence.database.storageClass | quote }}
{{- end }}
{{- end }}