apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contao-cms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contao-cms.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "database.url" . }}
  DATABASE_PASSWORD: {{ include "database.password" . | b64enc | quote }}
  DATABASE_ROOT_PASSWORD: {{ include "database.rootpassword" . | b64enc | quote }}
  
