apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deconz.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deconz.labels" . | nindent 4 }}
type: Opaque
data:
  vnc_password: {{ .Values.vnc.password | default (randAlphaNum 32) | b64enc | quote }}
  
